# Generated by Django 3.0.6 on 2020-05-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60000)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60000, unique=True)),
                ('characters', models.ManyToManyField(to='litapi.Character')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=60000)),
                ('order', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litapi.Quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CharacterDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=60000)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litapi.Character')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litapi.Quiz')),
            ],
            options={
                'ordering': ['body'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litapi.Source'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=60000)),
                ('characters', models.ManyToManyField(to='litapi.Character')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litapi.Question')),
            ],
            options={
                'ordering': ['body'],
            },
        ),
    ]
